version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: "1100:1100"  # 指定 UID:GID
    ports:
      - "8080:80"
    volumes:
      - /:/srv
      - /opt/filebrowser/database:/database
      - /opt/filebrowser/config:/config
    restart: unless-stopped
